// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(cb, socket) {
    var admin, db, dbOrig, out;
    if (!cb.socket.mongo || !cb.socket.mongo.database) {
      return cb("Not connected");
    }
    out = {};
    db = cb.socket.mongo.database;
    admin = db.admin;
    if (db._dbconn.options) {
      dbOrig = db._dbconn.databaseName;
      db._dbconn.databaseName = "admin";
      return db.open(function(err, r) {
        db._dbconn.databaseName = dbOrig;
        return db.open(function(err, r) {
          return db.collectionNames(function(err, r) {
            if (err != null) {
              return cb(err.message);
            }
            out.collections = r;
            return admin.serverStatus(function(err, r) {
              if (err == null) {
                out.serverStatus = r;
              }
              return admin.buildInfo(function(err, r) {
                if (err == null) {
                  out.buildInfo = r;
                }
                return admin.profilingLevel(function(err, r) {
                  if (err == null) {
                    out.profilingLevel = r;
                  }
                  return admin.profilingInfo(function(err, r) {
                    if (err == null) {
                      out.profilingInfo = r;
                    }
                    return admin.replSetGetStatus(function(err, r) {
                      if (err == null) {
                        out.replSetGetStatus = r;
                      }
                      return cb(null, out);
                    });
                  });
                });
              });
            });
          });
        });
      });
    }
  };

}).call(this);
