// Generated by CoffeeScript 1.6.3
(function() {
  var mongo;

  mongo = require('mongoskin');

  module.exports = function(cb, host) {
    var db, _ref;
    if (typeof host !== 'string') {
      return cb("Missing connection string");
    }
    if (((_ref = cb.socket.mongo) != null ? _ref.database : void 0) != null) {
      return cb(null, true);
    }
    cb.socket.mongo = {};
    db = cb.socket.mongo.database = mongo.db(host, {
      safe: true
    });
    return cb(null, true);
  };

}).call(this);
