// Generated by CoffeeScript 1.6.3
(function() {
  var BSON, formatDocuments, prettify, tasks, ton, uglify;

  ton = require("mongo-ton");

  uglify = require("uglify-js");

  BSON = require('mongodb').pure().BSON;

  ObjectID = require('mongodb').pure().ObjectID;

  jobs = new (require('../../../jobs/manager'));

  prettify = function(code) {
    var err, ish;
    try {
      ish = uglify.uglify.gen_code(uglify.parser.parse("(" + code + ")"), {
        beautify: true,
        quote_keys: true
      });
      return ish.substring(1, ish.length - 2);
    } catch (_error) {
      err = _error;
      console.log(code, err);
      return "Error parsing JS " + err.message;
    }
  };

  formatSyncUsers = function(res) {
    var doc, out, _i, _len;
    out = [];
    for (_i = 0, _len = res.length; _i < _len; _i++) {
      doc = res[_i];
      out.push({
        _id: doc._id,
        //TODO: how can we get the items information?
        itemCount: 12,
        noScreenshotCount: 13,
        noFaviconCount: 222,
        email: doc.email
      });
    }
    return out;
  };

  tasks = {
    
    syncinfo: function(command, cb) {
      if (command.query == null) {
        return cb("Missing query");
      }
      if (command.options == null) {
        command.options = {};
      }
      var col = cb.socket.mongo.database.collection("users");
      return col.find(command.query, command.options).toArray(function(err, res) {
        if (err != null) {
          return cb(err);
        }
        if (res == null) {
          return cb(null, []);
        }
        return cb(null, formatSyncUsers(res));
      });
    },

    syncFaviconForUSer: function(command, cb) {
      if (command.userId == null) {
        return cb("Missing userId");
      }

      var col = cb.socket.mongo.database.collection("items");
      return col.find({user:  ObjectID.createFromHexString(command.userId) ,favicon: null}).toArray(function(err, res) {
        if (err != null) {
          return cb(err);
        }
        if (res == null) {
          return cb(null, []);
        }

        for (_i = 0, _len = res.length; _i < _len; _i++) {
          var item = res[_i];
          jobs.schedule('check url', {
            uri: item.url,
            uniqueId: item._id.toString()
          }).on('complete', function() {
              item.favicon = "/screenshots/" + item._id.toString() + "/favicon.png";              
              col.save(item);
          })
        }

        return cb(null);
      });
    },
    
    syncScreenshotForUSer: function(command, cb) {
      if (command.userId == null) {
        return cb("Missing userId");
      }

      var col = cb.socket.mongo.database.collection("items");
      return col.find({user:  ObjectID.createFromHexString(command.userId) ,screenshot: null}).toArray(function(err, res) {
        if (err != null) {
          return cb(err);
        }
        if (res == null) {
          return cb(null, []);
        }

        for (_i = 0, _len = res.length; _i < _len; _i++) {
          var item = res[_i];
          jobs.schedule('screenshot', {
            uri: item.url,
            uniqueId: item._id.toString()
          }).on('complete', function() {
              item.screenshot = "/screenshots/" + item._id.toString() + "/screenshot.jpg";            
              col.save(item);
          })
        }

        return cb(null);
      });
    }

  };

  module.exports = function(cb, command) {
    var err;
    if (cb.socket == null) {
      return;
    }
    if (cb.socket.mongo == null) {
      return cb("Not connected");
    }
    if (command == null) {
      return cb("Missing command");
    }
    if (command.type == null) {
      return cb("Missing type");
    }
    if (tasks[command.type] == null) {
      return cb("Invalid command");
    }    
    if ((command.query != null) && typeof command.query === 'string') {
      try {
        command.query = ton.parse(command.query);
      } catch (_error) {
        err = _error;
        return cb(err.message);
      }
    }
    return tasks[command.type](command, cb);
  };

}).call(this);
