// Generated by CoffeeScript 1.6.3
(function() {
  var Pane, Vein, app, err, express, http, join, opt, port, server, vein;

  express = require("express");

  http = require("http");

  join = require("path").join;

  Vein = require('vein');

  port = 5000;

  app = express();

  app.use(express.staticCache());

  app.use(express["static"](join(__dirname, './public/')));

  server = http.createServer(app).listen(port);

  vein = Vein.createServer(server);

  vein.addFolder(join(__dirname, './lib/services/'));

  console.log("Server started on " + port);

  if (process.argv[2] === '-u') {
    try {
      Pane = require('pane');
      opt = {
        title: "Smog",
        height: 700,
        width: 1200,
        url: "http://localhost:" + port
      };
      process.nextTick(function() {
        var window;
        window = new Pane(opt);
        return window.open();
      });
    } catch (_error) {
      err = _error;
      console.log('You need to install libqtwebkit-dev to use the desktop UI.');
    }
  }

}).call(this);
