var config = require('../../config');

//Search tips
exports.searchtips = function (req, res, next) {
  res.render('modals/searchtips');
}
//Bookmarklet
exports.bookmarklet = function (req, res, next) {
  res.render('modals/bookmarklet', {//TODO we should either read it from somewhere and cache, or compile
    archiveCode: 'javascript:(function(e){var t="' + config.appUrl + '";if(t!==location.protocol+"//"+location.host){var n=e.document;var r=n.createElement("div");var i=n.documentElement.outerHTML;setTimeout(function(){function u(e){return encodeURIComponent(e).replace(/%20/g,"+")}function a(r,s){var o=new XMLHttpRequest;o.open("POST",t+"/bookmarklet/add",true);o.setRequestHeader("Content-type","application/x-www-form-urlencoded");o.withCredentials=true;o.onreadystatechange=function(){if(s&&o.readyState==4)s(JSON.parse(o.responseText)._id)};o.send("url="+u(e.location.href)+"&parent="+u(r)+"&title="+u(n.title)+"&width="+u(n.documentElement.clientWidth)+"&height="+u(n.documentElement.clientHeight)+"&html="+u(i)+"&charset="+u(n.characterSet)+"&v=1.1")}function f(e){r.innerHTML="<div style=\'position:absolute;margin:auto;top:0;right:0;bottom:0;text-align:center;width:100%;height:48px;z-index:-100;font-size: 24px;font-weight: bold;color: #ff6d16;\'>"+e+"</div>"}function l(){f("Added!");setTimeout(function(){n.body.removeChild(r);r=null},2e3)}function c(e){if(e.origin!==t)return;if(e.data.substring(0,5)==="save_"){var r=n.getElementById(s);if(r){n.body.removeChild(r);r=null}f("Adding...");a(e.data.substring(5),l)}else switch(e.data){case"destroy":destroy();break}}var s="BPIPE_bookmarklet_iframe",o=n.getElementById(s);if(o){return}var h=n.createElement("iframe");h.id=s;h.src=t+"/bookmarklet/archive";f("<img src=\'"+t+"/img/loader.gif\'/>");r.style.backgroundColor="#FFF";r.style.position=h.style.position="fixed";r.style.top=h.style.top="0";r.style.right=h.style.right="0";r.style.height=h.style.height="100%";r.style.width=h.style.width="269px";r.style.zIndex=h.style.zIndex="1999999999";r.style.borderLeft=h.style.borderLeft="6px solid #ff6d16";r.style.borderRight=h.style.borderRight=r.style.borderTop=h.style.borderTop=r.style.borderBottom=h.style.borderBottom="none";h.style.visibility="hidden";h.onload=function(){this.style.visibility="visible"};n.body.appendChild(r);n.body.appendChild(h);var p=e.addEventListener?"addEventListener":"attachEvent";var v=p=="attachEvent"?"onmessage":"message";e[p](v,c,false)},1)}})(window)',
    laterCode: 'javascript:(function(e){var t="' + config.appUrl +'";if(t!==location.protocol+"//"+location.host){var n=e.document;var r=n.createElement("div");var i=n.documentElement.outerHTML;setTimeout(function(){function u(e){return encodeURIComponent(e).replace(/%20/g,"+")}function a(r){var s=new XMLHttpRequest;s.open("POST",t+"/bookmarklet/add",true);s.setRequestHeader("Content-type","application/x-www-form-urlencoded");s.withCredentials=true;s.onreadystatechange=function(){if(r&&s.readyState==4)r(JSON.parse(s.responseText)._id)};s.send("url="+u(e.location.href)+"&title="+u(n.title)+"&width="+u(n.documentElement.clientWidth)+"&height="+u(n.documentElement.clientHeight)+"&html="+u(i)+"&charset="+u(n.characterSet)+"&v=1.1")}function f(e){r.innerHTML="<div style=\'position:absolute;margin:auto;top:0;right:0;bottom:0;text-align:center;width:100%;height:48px;z-index:-100;font-size: 24px;font-weight: bold;color: #ff6d16;\'>"+e+"</div>"}function l(){f("Added!");setTimeout(function(){n.body.removeChild(r);r=null},2e3)}function c(e){if(e.origin!==t)return;switch(e.data){case"save":{var r=n.getElementById(s);if(r){n.body.removeChild(r);r=null}f("Adding...");a(l);break}}}var s="BPIPE_bookmarklet_iframe",o=n.getElementById(s);if(o){return}var h=n.createElement("iframe");h.id=s;h.src=t+"/bookmarklet/open";f("<img src=\'"+t+"/img/loader.gif\'/>");r.style.backgroundColor="#FFF";r.style.position=h.style.position="fixed";r.style.top=h.style.top="0";r.style.right=h.style.right="0";r.style.height=h.style.height="100%";r.style.width=h.style.width="269px";r.style.zIndex=h.style.zIndex="1999999999";r.style.borderLeft=h.style.borderLeft="6px solid #ff6d16";r.style.borderRight=h.style.borderRight=r.style.borderTop=h.style.borderTop=r.style.borderBottom=h.style.borderBottom="none";h.style.visibility="hidden";h.onload=function(){this.style.visibility="visible"};n.body.appendChild(r);n.body.appendChild(h);var p=e.addEventListener?"addEventListener":"attachEvent";var v=p=="attachEvent"?"onmessage":"message";e[p](v,c,false)},1)}})(window)',
    openCode: 'javascript:(function(e){var t="' + config.appUrl + '";if(t!==location.protocol+"//"+location.host){var n=e.document;var r=n.createElement("div");var i=n.documentElement.outerHTML;setTimeout(function(){function u(e){return encodeURIComponent(e).replace(/%20/g,"+")}function a(r){var s=new XMLHttpRequest;s.open("POST",t+"/bookmarklet/add",true);s.setRequestHeader("Content-type","application/x-www-form-urlencoded");s.withCredentials=true;s.onreadystatechange=function(){if(r&&s.readyState==4)r(JSON.parse(s.responseText)._id)};s.send("url="+u(e.location.href)+"&title="+u(n.title)+"&width="+u(n.documentElement.clientWidth)+"&height="+u(n.documentElement.clientHeight)+"&html="+u(i)+"&charset="+u(n.characterSet)+"&v=1.1")}function f(e){r.innerHTML="<div style=\'position:absolute;margin:auto;top:0;right:0;bottom:0;text-align:center;width:100%;height:48px;z-index:-100;font-size: 24px;font-weight: bold;color: #ff6d16;\'>"+e+"</div>"}function l(e){f("Redirecting...");window.location=t+"/item/"+e}function c(e){if(e.origin!==t)return;switch(e.data){case"save":{var r=n.getElementById(s);if(r){n.body.removeChild(r);r=null}f("Adding...");a(l);break}}}var s="BPIPE_bookmarklet_iframe",o=n.getElementById(s);if(o){return}var h=n.createElement("iframe");h.id=s;h.src=t+"/bookmarklet/open";f("<img src=\'"+t+"/img/loader.gif\'/>");r.style.backgroundColor="#FFF";r.style.position=h.style.position="fixed";r.style.top=h.style.top="0";r.style.right=h.style.right="0";r.style.height=h.style.height="100%";r.style.width=h.style.width="269px";r.style.zIndex=h.style.zIndex="1999999999";r.style.borderLeft=h.style.borderLeft="6px solid #ff6d16";r.style.borderRight=h.style.borderRight=r.style.borderTop=h.style.borderTop=r.style.borderBottom=h.style.borderBottom="none";h.style.visibility="hidden";h.onload=function(){this.style.visibility="visible"};n.body.appendChild(r);n.body.appendChild(h);var p=e.addEventListener?"addEventListener":"attachEvent";var v=p=="attachEvent"?"onmessage":"message";e[p](v,c,false)},1)}})(window)'
  })
}
